"""changename source_link_columm

Revision ID: 805bdea7da1f
Revises: d200cfe8c4cf
Create Date: 2024-11-21 15:48:58.879739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '805bdea7da1f'
down_revision: Union[str, None] = 'd200cfe8c4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_link', sa.Column('source_link', sa.String(), nullable=True))
    op.drop_column('tg_link', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_link', sa.Column('source', sa.VARCHAR(), nullable=True))
    op.drop_column('tg_link', 'source_link')
    # ### end Alembic commands ###
