"""Added 2 column

Revision ID: 92e3257fceb1
Revises: 805bdea7da1f
Create Date: 2024-11-21 23:23:18.999416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e3257fceb1'
down_revision: Union[str, None] = '805bdea7da1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_link', sa.Column('id_database_notion', sa.String(), nullable=True))
    op.add_column('tg_link', sa.Column('token_integration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_link', 'token_integration')
    op.drop_column('tg_link', 'id_database_notion')
    # ### end Alembic commands ###
