"""added table and drop column

Revision ID: b6a4338a76ca
Revises: 92e3257fceb1
Create Date: 2024-11-22 00:30:08.280136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6a4338a76ca'
down_revision: Union[str, None] = '92e3257fceb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notion_id_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user_tg', sa.BigInteger(), nullable=False),
    sa.Column('database_id', sa.String(), nullable=True),
    sa.Column('integration_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('tg_link', 'token_integration')
    op.drop_column('tg_link', 'id_database_notion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_link', sa.Column('id_database_notion', sa.VARCHAR(), nullable=True))
    op.add_column('tg_link', sa.Column('token_integration', sa.VARCHAR(), nullable=True))
    op.drop_table('notion_id_token')
    # ### end Alembic commands ###
